version: 2

sources:
  - name: raw_data
    description: "Raw data souces for NYC taxi rides"
    database: terra-77564 # Project ID
    freshness:
      warn_after: { count: 120, period: day }
      error_after: { count: 240, period: day }
    schema: nytaxi # Dataset name
    tables:
      - name: yellow_tripdata
        description: "Raw green taxi trip data"
        columns:
          - name: VendorID
            description: |
              A code indicating the provider associated with the trip record.
                  1: 'Creative Mobile Technologies, LLC.'
                  2: 'VeriFone Inc.'
                  4: 'Unknown Vendor'
            data_type: integer
            meta:
              pii: false
              ownership: data_team
              importance: high
              formatting: none
      - name: green_tripdata
        description: "Raw yellow taxi trip data"
      - name: fhv_tripdata_2019
        description: "For-Hire Vehicle (FHV) trip data for 2019"
